update platform_settings
set value = jsonb_set(
  coalesce(value, '{}'::jsonb),
  '{am}',
  coalesce(value->'am', '{}'::jsonb) || '{
    "meta_step_label":"ደረጃ 1: መሠረታዊ መረጃ",
    "caption_country":"አገር",
    "caption_form_language":"የቅጽ ቋንቋ",
    "caption_input_language":"የግቤት ቋንቋ",
    "caption_procedure_type":"የሂደት አይነት",
    "caption_use_different_input_language":"የተለየ የግቤት ቋንቋ እጠቀማለሁ",
    "help_country":"ይህ ጉዳይ እንዲሰራ የሚያስፈልገውን አገር ይምረጡ።",
    "help_form_language":"በቅጹ ላይ የሚታዩ ጽሑፎች እና መመሪያዎች የሚታዩበት ቋንቋ ነው።",
    "help_input_language":"መረጃውን ለመጻፍ የሚጠቀሙበት ቋንቋ ነው።",
    "help_procedure_type":"ይህ ጉዳይ የቅሬታ ሪፖርት ነው ወይስ የጥቆማ ሪፖርት እንደሆነ ይምረጡ።",
    "field_subject":"የሪፖርት ርዕስ",
    "field_description":"መግለጫ",
    "field_incident_date":"የክስተት ቀን",
    "field_incident_location":"የክስተት ቦታ",
    "field_continuing":"ክስተቱ እየቀጠለ ነው?",
    "field_suggested_remedy":"የተጠቆመ መፍትሄ",
    "field_legal_steps":"የተወሰዱ የሕግ እርምጃዎች",
    "field_files":"ፋይሎች",
    "field_reported_company":"የተሪፖርት ድርጅት",
    "field_direct_customers":"ቀጥተኛ ደንበኞች",
    "field_indirect_customers":"ቀጥተኛ ያልሆኑ ደንበኞች",
    "field_ngo_representation":"በኤንጂኦ ወክልና",
    "field_reporter_email":"የሪፖርተር ኢሜይል",
    "field_share_contact":"የግንኙነት መረጃዬን ከድርጅቱ ጋር አጋራ",
    "help_subject":"አጭር እና ግልጽ ርዕስ ይጻፉ።",
    "help_description":"ምን እንደተከሰተ፣ መቼ እና የት እንደተከሰተ በግልጽ ይጻፉ።",
    "help_incident_date":"ክስተቱ የተከሰተበትን ቀን ይምረጡ።",
    "help_incident_location":"ክስተቱ የተከሰተበትን ቦታ ያስገቡ።",
    "help_continuing":"ጉዳዩ አሁንም እየቀጠለ ከሆነ \"አዎ\" ይምረጡ።",
    "help_suggested_remedy":"የሚጠበቀው መፍትሄ ምን እንደሆነ ይግለጹ።",
    "help_legal_steps":"ቀደም ሲል የተወሰዱ የሕግ ወይም የአስተዳደር እርምጃዎች ካሉ ያስገቡ።",
    "help_files":"ደጋፊ ማስረጃ ፋይሎች (ፎቶ፣ ሰነድ፣ ድምጽ) ያክሉ።",
    "help_reported_company":"ስለሚመለከተው ድርጅት ይምረጡ።",
    "help_direct_customers":"ቀጥተኛ የንግድ ግንኙነት ያላቸውን ደንበኞች ይምረጡ።",
    "help_indirect_customers":"በቀጥታ ያልተገናኙ ነገር ግን የሚመለከቱ ደንበኞች ካሉ ይምረጡ።",
    "help_ngo_representation":"በሌላ ሰው ስም እያቀረቡ ከሆነ ይህን ይምረጡ።",
    "help_reporter_email":"ለክትትል እና ምላሽ የሚጠቅም ኢሜይል ያስገቡ።",
    "help_share_contact":"ድርጅቱ በቀጥታ እንዲገናኝዎ ከፈለጉ ይህን ይምረጡ።",
    "cta_next":"ቀጣይ",
    "cta_back":"ተመለስ",
    "cta_submit":"ሪፖርት ላክ",
    "cta_save_draft":"ረቂቅ አስቀምጥ",
    "sys_loading":"እየጫነ ነው...",
    "sys_required":"ይህ መስክ አስፈላጊ ነው።",
    "sys_invalid_email":"የተሳሳተ የኢሜይል ቅርጸት።",
    "sys_fix_errors":"እባክዎ ስህተቶቹን አስተካክለው ይቀጥሉ።",
    "sys_submit_success":"ሪፖርትዎ በተሳካ ሁኔታ ተልኳል።",
    "sys_submit_failed":"ሪፖርት መላክ አልተሳካም። ደግመው ይሞክሩ።",
    "accessibility_audio_on":"የድምጽ ማንበብ ክፍት",
    "accessibility_audio_off":"የድምጽ ማንበብ ጠፍቷል",
    "accessibility_easy_read_on":"ቀላል ንባብ ክፍት",
    "accessibility_easy_read_off":"ቀላል ንባብ ጠፍቷል"
  }'::jsonb,
  true
)
where key = 'intake_i18n_copy';
